# DomainParticipantFactoryQos default QoS values
DomainParticipantFactoryQosProfileChild.entityFactory.autoenableCreatedEntities = true
DomainParticipantFactoryQosProfileChild.resourceLimits.maxParticipants = 1
DomainParticipantFactoryQosProfileChild.resourceLimits.maxComponents = 16
# DomainParticipantQos default QoS values
DomainParticipantQosProfileChild.entityFactory.autoenableCreatedEntities = true
DomainParticipantQosProfileChild.discovery.acceptUnknownPeers = true
DomainParticipantQosProfileChild.discovery.enableParticipantDiscoveryByName = false
DomainParticipantQosProfileChild.discovery.enableEndpointDiscoveryQueue = false
DomainParticipantQosProfileChild.resourceLimits.localWriterAllocation.maxCount = 1
DomainParticipantQosProfileChild.resourceLimits.localReaderAllocation.maxCount = 1
DomainParticipantQosProfileChild.resourceLimits.localPublisherAllocation.maxCount = 1
DomainParticipantQosProfileChild.resourceLimits.localSubscriberAllocation.maxCount = 1
DomainParticipantQosProfileChild.resourceLimits.localTopicAllocation.maxCount = 1
DomainParticipantQosProfileChild.resourceLimits.localTypeAllocation.maxCount = 1
DomainParticipantQosProfileChild.resourceLimits.remoteParticipantAllocation.maxCount = 1
DomainParticipantQosProfileChild.resourceLimits.remoteWriterAllocation.maxCount = 1
DomainParticipantQosProfileChild.resourceLimits.remoteReaderAllocation.maxCount = 1
DomainParticipantQosProfileChild.resourceLimits.matchingWriterReaderPairAllocation.maxCount = 32
DomainParticipantQosProfileChild.resourceLimits.matchingReaderWriterPairAllocation.maxCount = 32
DomainParticipantQosProfileChild.resourceLimits.maxReceivePorts = 8
DomainParticipantQosProfileChild.resourceLimits.maxDestinationPorts = 8
DomainParticipantQosProfileChild.resourceLimits.shmemRefTransferModeMaxSegments = 500
DomainParticipantQosProfileChild.resourceLimits.participantUserDataMaxLength = 0
DomainParticipantQosProfileChild.resourceLimits.participantUserDataMaxCount = DDS_SIZE_AUTO
DomainParticipantQosProfileChild.resourceLimits.topicDataMaxLength = 0
DomainParticipantQosProfileChild.resourceLimits.topicDataMaxCount = DDS_SIZE_AUTO
DomainParticipantQosProfileChild.resourceLimits.publisherGroupDataMaxLength = 0
DomainParticipantQosProfileChild.resourceLimits.publisherGroupDataMaxCount = DDS_SIZE_AUTO
DomainParticipantQosProfileChild.resourceLimits.subscriberGroupDataMaxLength = 0
DomainParticipantQosProfileChild.resourceLimits.subscriberGroupDataMaxCount = DDS_SIZE_AUTO
DomainParticipantQosProfileChild.resourceLimits.writerUserDataMaxLength = 0
DomainParticipantQosProfileChild.resourceLimits.writerUserDataMaxCount = DDS_SIZE_AUTO
DomainParticipantQosProfileChild.resourceLimits.readerUserDataMaxLength = 0
DomainParticipantQosProfileChild.resourceLimits.readerUserDataMaxCount = DDS_SIZE_AUTO
DomainParticipantQosProfileChild.resourceLimits.maxPartitions = 64
DomainParticipantQosProfileChild.resourceLimits.maxPartitionCumulativeCharacters = 256
DomainParticipantQosProfileChild.resourceLimits.maxPartitionStringSize = LENGTH_UNLIMITED
DomainParticipantQosProfileChild.resourceLimits.maxPartitionStringAllocation = LENGTH_UNLIMITED
DomainParticipantQosProfileChild.resourceLimits.participantPropertyListMaxLength = 1
DomainParticipantQosProfileChild.resourceLimits.participantPropertyStringMaxLength = 32
DomainParticipantQosProfileChild.resourceLimits.writerPropertyListMaxLength = 1
DomainParticipantQosProfileChild.resourceLimits.writerPropertyStringMaxLength = 32
DomainParticipantQosProfileChild.resourceLimits.readerPropertyListMaxLength = 0
DomainParticipantQosProfileChild.resourceLimits.readerPropertyStringMaxLength = 0
DomainParticipantQosProfileChild.wireProtocol.participantId = -1
DomainParticipantQosProfileChild.wireProtocol.rtpsHostId = RTPS_AUTO_ID
DomainParticipantQosProfileChild.wireProtocol.rtpsAppId = RTPS_AUTO_ID
DomainParticipantQosProfileChild.wireProtocol.rtpsInstanceId = RTPS_AUTO_ID
DomainParticipantQosProfileChild.wireProtocol.rtpsWellKnownPorts.portBase = 7400
DomainParticipantQosProfileChild.wireProtocol.rtpsWellKnownPorts.domainIdGain = 250
DomainParticipantQosProfileChild.wireProtocol.rtpsWellKnownPorts.participantIdGain = 2
DomainParticipantQosProfileChild.wireProtocol.rtpsWellKnownPorts.builtinMulticastPortOffset = 0
DomainParticipantQosProfileChild.wireProtocol.rtpsWellKnownPorts.builtinUnicastPortOffset = 10
DomainParticipantQosProfileChild.wireProtocol.rtpsWellKnownPorts.userMulticastPortOffset = 1
DomainParticipantQosProfileChild.wireProtocol.rtpsWellKnownPorts.userUnicastPortOffset = 11
DomainParticipantQosProfileChild.wireProtocol.computeCrc = false
DomainParticipantQosProfileChild.wireProtocol.checkCrc = false
DomainParticipantQosProfileChild.wireProtocol.requireCrc = false
DomainParticipantQosProfileChild.wireProtocol.computedCrcKind = CHECKSUM_AUTO
DomainParticipantQosProfileChild.wireProtocol.allowedCrcMask = CHECKSUM_AUTO
DomainParticipantQosProfileChild.filterQosPolicy.disableWriterFiltering = false
DomainParticipantQosProfileChild.filterQosPolicy.disableBuiltinSqlFilter = false
DomainParticipantQosProfileChild.filterQosPolicy.resourceLimits.filterClassMaxLength = 7
DomainParticipantQosProfileChild.filterQosPolicy.resourceLimits.filterClassMaxCount = 1
DomainParticipantQosProfileChild.filterQosPolicy.resourceLimits.filterExpressionMaxLength = 63
DomainParticipantQosProfileChild.filterQosPolicy.resourceLimits.filterExpressionMaxCount = LENGTH_AUTO
DomainParticipantQosProfileChild.filterQosPolicy.resourceLimits.filterParameterMaxCountPerExpression = 4
DomainParticipantQosProfileChild.filterQosPolicy.resourceLimits.filterParameterMaxLength = 15
DomainParticipantQosProfileChild.filterQosPolicy.sqlPredicateMaxCountPerExpression = NULL
# Discovery
DomainParticipantQosProfileChild.discoveryConfig.participantLivelinessAssertPeriod.sec = 30
DomainParticipantQosProfileChild.discoveryConfig.participantLivelinessAssertPeriod.nanosec = 0
DomainParticipantQosProfileChild.discoveryConfig.participantLivelinessLeaseDuration.sec = 100
DomainParticipantQosProfileChild.discoveryConfig.participantLivelinessLeaseDuration.nanosec = 0
DomainParticipantQosProfileChild.discoveryConfig.initialParticipantAnnouncements = 5
DomainParticipantQosProfileChild.discoveryConfig.cacheSerializedSamples = false
DomainParticipantQosProfileChild.discoveryConfig.maxParticipantLocators = LENGTH_AUTO
DomainParticipantQosProfileChild.discoveryConfig.maxLocatorsPerDiscoveredParticipant = 4
DomainParticipantQosProfileChild.discoveryConfig.subscriptionReaderResourceLimits.maxSamples = 8
DomainParticipantQosProfileChild.discoveryConfig.publicationWriter.maxHeartbeatRetries = LENGTH_UNLIMITED
DomainParticipantQosProfileChild.discoveryConfig.publicationWriter.heartbeatPeriod.sec = 0
DomainParticipantQosProfileChild.discoveryConfig.publicationWriter.heartbeatPeriod.nanosec = 100000000
DomainParticipantQosProfileChild.discoveryConfig.publicationWriter.heartbeatsPerMaxSamples = -1
DomainParticipantQosProfileChild.discoveryConfig.subscriptionReader.nackPeriod.sec = 0
DomainParticipantQosProfileChild.discoveryConfig.subscriptionReader.nackPeriod.nanosec = 50000000
# UDP_Transport QoS
DomainParticipantQosProfileChild.transportBuiltin.udpv4.ignoreLoopbackInterface = -1
DomainParticipantQosProfileChild.transportBuiltin.udpv4.sendSocketBufferSize = 262144
DomainParticipantQosProfileChild.transportBuiltin.udpv4.recvSocketBufferSize = 262144
DomainParticipantQosProfileChild.transportBuiltin.udpv4.messageSizeMax = 8192
DomainParticipantQosProfileChild.transportBuiltin.udpv4.multicastTtl = 1
DomainParticipantQosProfileChild.transportBuiltin.udpv4.disableAutoInterfaceConfig = false
DomainParticipantQosProfileChild.transportBuiltin.udpv4.multicastLoopbackDisabled = false
DomainParticipantQosProfileChild.transportBuiltin.udpv4.maxUnicastSendSockets = 1
DomainParticipantQosProfileChild.transportBuiltin.udpv4.transportPriorityMappingHigh = 255
DomainParticipantQosProfileChild.transportBuiltin.udpv4.transportPriorityMappingLow = 0
DomainParticipantQosProfileChild.transportBuiltin.udpv4.transportPriorityMask = 0
# NETIO_SHMEMInterfaceFactoryProperty
DomainParticipantQosProfileChild.transportBuiltin.shmem.receivedMessageCountMax = 64
DomainParticipantQosProfileChild.transportBuiltin.shmem.receiveBufferSize = 1048576
DomainParticipantQosProfileChild.transportBuiltin.shmem.messageSizeMax = 65536
# DataWriterQos default QoS values
DataWriterQosProfileChild.deadline.period.sec = DURATION_INFINITE_SEC
DataWriterQosProfileChild.deadline.period.nanosec = DURATION_INFINITE_NSEC
DataWriterQosProfileChild.liveliness.kind = AUTOMATIC_LIVELINESS_QOS
DataWriterQosProfileChild.liveliness.leaseDuration.sec = DURATION_INFINITE_SEC
DataWriterQosProfileChild.liveliness.leaseDuration.nanosec = DURATION_INFINITE_NSEC
DataWriterQosProfileChild.history.kind = KEEP_LAST_HISTORY_QOS
DataWriterQosProfileChild.history.depth = 1
DataWriterQosProfileChild.resourceLimits.maxSamples = 1
DataWriterQosProfileChild.resourceLimits.maxInstances = 1
DataWriterQosProfileChild.resourceLimits.maxSamplesPerInstance = 1
DataWriterQosProfileChild.ownership.kind = SHARED_OWNERSHIP_QOS
DataWriterQosProfileChild.ownershipStrength.value = 0
DataWriterQosProfileChild.latencyBudget.duration.sec = 0
DataWriterQosProfileChild.latencyBudget.duration.nanosec = 0
DataWriterQosProfileChild.reliability.kind = RELIABLE_RELIABILITY_QOS
DataWriterQosProfileChild.reliability.maxBlockingTime.sec = 0
DataWriterQosProfileChild.reliability.maxBlockingTime.nanosec = 100000000
DataWriterQosProfileChild.durability.kind = VOLATILE_DURABILITY_QOS
DataWriterQosProfileChild.destinationOrder.kind = BY_RECEPTION_TIMESTAMP_DESTINATIONORDER_QOS
DataWriterQosProfileChild.destinationOrder.sourceTimestampTolerance.sec = 0
DataWriterQosProfileChild.destinationOrder.sourceTimestampTolerance.nanosec = 100000000
DataWriterQosProfileChild.protocol.rtpsObjectId = RTPS_AUTO_ID
DataWriterQosProfileChild.protocol.rtpsReliableWriter.heartbeatPeriod.sec = 3
DataWriterQosProfileChild.protocol.rtpsReliableWriter.heartbeatPeriod.nanosec = 0
DataWriterQosProfileChild.protocol.rtpsReliableWriter.heartbeatsPerMaxSamples = 1
DataWriterQosProfileChild.protocol.rtpsReliableWriter.maxSendWindowSize = LENGTH_UNLIMITED
DataWriterQosProfileChild.protocol.rtpsReliableWriter.maxHeartbeatRetries = LENGTH_UNLIMITED
DataWriterQosProfileChild.writerResourceLimits.maxRemoteReaders = 16
DataWriterQosProfileChild.writerResourceLimits.maxRoutesPerReader = 4
DataWriterQosProfileChild.writerResourceLimits.writerLoanedSampleAllocation.maxCount = AUTO
DataWriterQosProfileChild.writerResourceLimits.initializeWriterLoanedSample = false
DataWriterQosProfileChild.writerResourceLimits.maxRemoteReaderFilters = LENGTH_UNLIMITED
DataWriterQosProfileChild.publishMode.priority = 0
DataWriterQosProfileChild.transferMode.shmemRefSettings.enableDataConsistencyCheck = true
DataWriterQosProfileChild.transportPriority.value = 0
# SubscriberQos
SubscriberQosProfileChild.presentation.accessScope = INSTANCE_PRESENTATION_QOS
SubscriberQosProfileChild.presentation.coherentAccess = false
SubscriberQosProfileChild.presentation.orderedAccess = false
# DataReaderQos default QoS values
DataReaderQosProfileChild.deadline.period.sec = DURATION_INFINITE_SEC
DataReaderQosProfileChild.deadline.period.nanosec = DURATION_INFINITE_NSEC
DataReaderQosProfileChild.liveliness.kind = AUTOMATIC_LIVELINESS_QOS
DataReaderQosProfileChild.liveliness.leaseDuration.sec = DURATION_INFINITE_SEC
DataReaderQosProfileChild.liveliness.leaseDuration.nanosec = DURATION_INFINITE_NSEC
DataReaderQosProfileChild.history.kind = KEEP_LAST_HISTORY_QOS
DataReaderQosProfileChild.history.depth = 1
DataReaderQosProfileChild.resourceLimits.maxSamples = 1
DataReaderQosProfileChild.resourceLimits.maxInstances = 1
DataReaderQosProfileChild.resourceLimits.maxSamplesPerInstance = 1
DataReaderQosProfileChild.ownership.kind = SHARED_OWNERSHIP_QOS
DataReaderQosProfileChild.latencyBudget.duration.sec = 0
DataReaderQosProfileChild.latencyBudget.duration.nanosec = 0
DataReaderQosProfileChild.reliability.kind = BEST_EFFORT_RELIABILITY_QOS
DataReaderQosProfileChild.reliability.maxBlockingTime.sec = 0
DataReaderQosProfileChild.reliability.maxBlockingTime.nanosec = 0
DataReaderQosProfileChild.durability.kind = VOLATILE_DURABILITY_QOS
DataReaderQosProfileChild.destinationOrder.kind = BY_RECEPTION_TIMESTAMP_DESTINATIONORDER_QOS
DataReaderQosProfileChild.destinationOrder.sourceTimestampTolerance.sec = 0
DataReaderQosProfileChild.destinationOrder.sourceTimestampTolerance.nanosec = 100000000
DataReaderQosProfileChild.protocol.rtpsObjectId = RTPS_AUTO_ID
DataReaderQosProfileChild.protocol.rtpsReliableReader.nackPeriod.sec = 0
DataReaderQosProfileChild.protocol.rtpsReliableReader.nackPeriod.nanosec = 50000000
DataReaderQosProfileChild.protocol.propagateDisposeOfUnregisteredInstances = true
DataReaderQosProfileChild.readerResourceLimits.maxRemoteWriters = 1
DataReaderQosProfileChild.readerResourceLimits.maxRemoteWritersPerInstance = 1
DataReaderQosProfileChild.readerResourceLimits.maxSamplesPerRemoteWriter = 1
DataReaderQosProfileChild.readerResourceLimits.maxOutstandingReads = 1
DataReaderQosProfileChild.readerResourceLimits.instanceReplacement.aliveInstanceRemoval = NO_INSTANCE_REMOVAL
DataReaderQosProfileChild.readerResourceLimits.instanceReplacement.disposedInstanceRemoval = NO_INSTANCE_REMOVAL
DataReaderQosProfileChild.readerResourceLimits.instanceReplacement.noWritersInstanceRemoval = NO_INSTANCE_REMOVAL
DataReaderQosProfileChild.readerResourceLimits.maxRoutesPerWriter = 4
DataReaderQosProfileChild.readerResourceLimits.maxFragmentedSamples = DDS_MAX_AUTO
DataReaderQosProfileChild.readerResourceLimits.maxFragmentedSamplesPerRemoteWriter = DDS_MAX_AUTO
DataReaderQosProfileChild.readerResourceLimits.shmemRefTransferModeAttachedSegmentAllocation.maxCount = DDS_SIZE_AUTO
DataReaderQosProfileChild.transportPriority.value = 0
# UdpInterfaceTableEntrySeq
UdpInterfaceTableEntrySeq.flags = 0
UdpInterfaceTableEntrySeq.address = 0
UdpInterfaceTableEntrySeq.netmask = 0
