#!/bin/bash
###############################################################################
# Copyright (c) 2016-2026 Real-Time Innovations, Inc. All rights reserved.
#
# No duplications, whole or partial, manual or electronic, may be made
# without express written permission.  Any such copies, or
# revisions thereof, must display this notice unaltered.
# This code contains trade secrets of Real-Time Innovations, Inc.
###############################################################################
BUILD_TYPE="Debug";
SCRIPT_NAME=$(basename "$0");
CMAKE_OPTIONS="";
CBUILD_OPTIONS="";
CMAKE_G="";
NAME="";
ARCH="";
NO_TEST=0;
CMAKE_PATH=""
GIT_BRANCH=""
DO_HELP=0
CMD_ECHO=
TOOLCHAIN_FILE=
SYSTEM_FILE=
PRE_BUILD=
ENABLE_QUACK=""

# Get the absolute path for the script
RDIR=$(pwd);
SDIR=$(dirname "$0");
cd "$SDIR" || exit 1;
SDIR=$(pwd);
SDIR=$(dirname "$(dirname "$SDIR")");
cd "$SDIR" || exit 1;
SDIR_SHORT=$(basename "$SDIR");
cd "$RDIR" || exit 1;

if [ -d "$SDIR/resource" ]; then
    DEVTREE=0;
    RESOURCE_DIR="$SDIR/resource/cmake";
elif [ "${SDIR_SHORT}_" = "ndds_lite_" ]; then
    DEVTREE=1;
    RESOURCE_DIR="$SDIR/resource.1.0/cmake";
else
    echo Unknown source-tree;
    exit -1;
fi;

print_help() {
    cat <<EOF

NAME

$SCRIPT_NAME

SYNOPSIS

$SCRIPT_NAME [options] [ -- cmake build options ]

Options:
  -h | --help         Print this help and exit.

  --gui               Launch the CMake GUI.

  --build             Build the target.

  --list              List available targets and exit.

  --config            Which type of build (Default: Debug):
                        - Debug   - Create a debug build.
                        - Release - Create a release build.

  --enable-quack      Enable Quack test bundles creation

  --delete            Delete existing, if any, target specific build directories

  --target <target>   Which target to compile for
                      The special target self is a self-hosted build with no
                      configuration.
  --name <name>       The name of the target. This is used as part of the
                      directory paths, as well as compiled into the target. If
                      --name is not specified, the --target is used as the name

  -G "generator"      Which CMake generator to use. Use cmake --help for a list
                      of available generators.

  --no-test           Do not build the unit-tests (only valid in the devtree)

  --git-branch        The Git branch to build (only valid in the devtree)

  --cmake-path        Path to cmake installation

  --source-dir        Path to CMakeLists.txt

  --srcdir            Path to CMakeLists.txt

  --dry-run           Only print the cmake commands that will be executed

  --tcfile file       Use the specified tool-chain file directly, ignoring
                      --target

  --sysfile file      Include this file as the system-file to modify flags
                      set by the toolchain (either with --target or
                      --tcfile).

  --cmake-target      Use the specified space separated list as the cmake
                      targets.

Unknown arguments before -- are concatenated and passed to cmake.
All arguments following -- are passed to cmake build.

DESCRIPTION

$SCRIPT_NAME is used to create architecture specific build files for
RTI Connext Micro and can optionally invoke the build.

EXAMPLES

Build Debug version on Linux, self hosted:

$SCRIPT_NAME --target self --name i86Linux2.6gcc4.4.5 --config Debug -G "Unix Makefiles" --build

Create an Eclipse project using a target specific buld-file and build using ninja

$SCRIPT_NAME --target i86Darwin13gcc4.9 --config Debug --delete -G "Eclipse CDT4 - Ninja" --build -- -j 8

Note the -- . The -- is used to indicate that all the following
arguments are to be passed to cmake build. The -- -j 8 tells cmake
build to pass -j 8 to ninja.

EOF

    exit 0;
}

print_error() {
    echo ERROR: $*;
}

print_warning() {
    echo WARN: $*;
}

print_info() {
    echo INFO: $*;
}

print_debug() {
    echo DEBUG: $*;
}

print_architectures() {
    if [ "$#" -eq 0 ]; then
        x=$(ls "$RESOURCE_DIR/architectures/"*.tc);
        print_info "The following architectures are available:";
    else
        x=$(ls "$RESOURCE_DIR/architectures/"*$1*.tc);
        print_info "The following architectures matches $1:";
    fi
    for x in $x; do
        print_info "$(basename "$x" .tc)";
    done;
    exit 0;
}

# A function to check the status of the last executed command.
check_cmake_status() {
    local last_command_status="$?"
    local command_name="$1"

    if [ "$last_command_status" -ne 0 ]; then
        print_error "$command_name failed with status $last_command_status."
        exit "$last_command_status"
    fi
}

while [ "$#" -gt 0 ]; do
    case $1 in
        -G)
            shift;
            CMAKE_G=$1;
        ;;
        --target)
            shift;
            ARCH=$1;
        ;;
        --source-dir | -s | --srcdir)
            SOURCE_DIR=$2;
            shift;
        ;;
        --cmake-path)
            shift;
            CMAKE_PATH=$1
        ;;
        --name)
            shift;
            NAME=$1;
        ;;
        -h | --help)
            DO_HELP=1;
        ;;
    	--gui)
    	   GUI="yes";
    	;;
        --build_env)
            shift;
            source "$RESOURCE_DIR/../scripts/$1";
        ;;
        --config)
            shift;
            BUILD_TYPE=$1;
        ;;
    	--build)
    	   DO_BUILD="yes";
	    ;;
    	--dry-run)
    	   CMD_ECHO=echo
	    ;;
        --tcfile)
            shift;
            TOOLCHAIN_FILE=$1;
        ;;
        --sysfile)
            shift;
            SYSTEM_FILE=$1;
        ;;
        --enable-quack)
            if [ $DEVTREE -eq 1 ]; then
                ENABLE_QUACK="-DRTIME_UTEST_QUACK_ENABLE=true"
            else
                print_error --enable-quack can only be used for the development tree;
                exit -1;
            fi
        ;;
	    --no-test)
            if [ $DEVTREE -eq 1 ]; then
                NO_TEST=1
            else
                print_error --no-test can only be used for the development tree;
                exit -1;
            fi
        ;;
        --git-branch)
            if [ $DEVTREE -eq 1 ]; then
                shift;
                GIT_BRANCH="-DRTI_BUILD_BRANCH=$1";
                BRANCH=$1;
            else
                print_error --git-branch can only be used for the development tree;
                exit -1;
            fi
        ;;
        --list)
            if [ "$#" -gt 0 ] ; then
                shift;
                print_architectures $1;
            else
                print_architectures;
            fi
        ;;
        --delete)
            DO_DELETE="yes";
        ;;
        --cmake-target)
            shift
            while [ "$#" -gt 0 ] && [[ "$1" != -* ]]; do
                CBUILD_OPTIONS="$CBUILD_OPTIONS $1"
                if [[ "$2" == -* ]]; then
                    break
                fi
                shift
            done
        ;;
    	--)
          shift;
          CBUILD_OPTIONS="$CBUILD_OPTIONS $*";
          break 2;
        ;;
        *)
            CMAKE_OPTIONS="$CMAKE_OPTIONS $1";
        ;;
    esac
    shift;
done

if [ "x$CMAKE_PATH" = "x" ]; then
    CMAKE_BIN=cmake;
    CMAKE_GUI=cmake-gui;
else
    CMAKE_BIN=$CMAKE_PATH/bin/cmake;
    CMAKE_GUI=$CMAKE_PATH/bin/cmake-gui;
fi

if [ "x$BUILD_TYPE" = "all" -o "x$BUILD_TYPE" = "All" ]; then
    BUILD_TYPE="Debug Release";
fi

if [ $DO_HELP -eq 1 ]; then
    if [ "x$ARCH" = "x" ]; then
        print_help;
    else
        $CMAKE_BIN -DTARGET_HELP:BOOLEAN=1 \
                   -DCMAKE_MODULE_PATH="$RESOURCE_DIR/architectures" \
                   -DRTIME_TARGET_NAME=$NAME \
                   -P "$RESOURCE_DIR/architectures/$ARCH.tc";
        check_cmake_status "CMake help"
    fi
    exit 0;
fi

# Flags only used when building Micro and not applications
if [ "x$SOURCE_DIR" = "x" ]; then
    if [ $DEVTREE -eq 1 ]; then
        if [ "x$BRANCH" = "x" ]; then
            BRANCH=`git branch | grep \* | cut -d' ' -f 2`;
            GIT_BRANCH="-DRTI_BUILD_BRANCH=$BRANCH";
        fi
    fi

    if [ $NO_TEST -eq 1 ]; then
        CMAKE_OPTIONS="$CMAKE_OPTIONS -DRTI_BUILD_UNITTESTS=FALSE";
    else
        CMAKE_OPTIONS="$CMAKE_OPTIONS -DRTI_BUILD_UNITTESTS=TRUE";
    fi

    CMAKE_OPTIONS="$CMAKE_OPTIONS -DRTIME_TARGET=$ARCH";
fi

if [ "x$ARCH" != "x" -a "x$TOOLCHAIN_FILE" != "x" ]; then
	    print_error "Only one of --target or --toolchain-file can be specified".
	    exit -1;
fi

if [ "x$ARCH" = "x" ]; then
	if [ "x$TOOLCHAIN_FILE" = "x" ]; then
	    print_error "The target must be specified with -t or --target or "
	    print_error "a toolchain file must be specified with --toolchain-file:"
	    print_error ""
	    print_error "--target target"
	    print_error ""
	    print_error "Use --list for available targets".
	    print_error ""
	    print_error "--toolchain-file file"
	    exit -1;
	else
		if [ ! -e $TOOLCHAIN_FILE ]; then
	        print_error The toolchain-file $TOOLCHAIN_FILE does not exist.
	        exit -1;
		else
			ARCH=$TOOLCHAIN_FILE
			TOOLCHAIN_FILE=-DCMAKE_TOOLCHAIN_FILE=$TOOLCHAIN_FILE;
		fi
		if [ "x$NAME" = "x" ]; then
	        print_error The name of the target must be specified with --name \<name\> when --toolchain-file is used.
	        exit -1;
		fi
	fi
else
    # strip of .tc just in case
    ARCH=$(basename "$ARCH" .tc);

    if [ "$ARCH" != "self" ]; then
        if [ -e "$RESOURCE_DIR/architectures/$ARCH.tc" ]; then
            TOOLCHAIN_FILE="-DCMAKE_TOOLCHAIN_FILE=$RESOURCE_DIR/architectures/$ARCH.tc";
        else
            print_error Unknown target $ARCH listed. use --list for a list of available targets.
            exit -1;
        fi
    fi
	if [ "x$NAME" = "x" ]; then
	    if [ "$ARCH" != "self" ]; then
	        NAME=$ARCH;
	    else
	        print_error The name of the target must be specified with --name \<name\> when --target self is used.
	        exit -1;
	    fi
	fi
fi

if [ "x$SYSTEM_FILE" != "x" ]; then
    if [ "$SYSTEM_FILE" != \"\" ]; then
        if [ ! -e "$SYSTEM_FILE" ]; then
		    print_error The system file $SYSTEM_FILE does not exist.
		    exit -1;
	    fi
    fi
    SYSTEM_FILE="-DRTIME_SYSTEM_FILE=$SYSTEM_FILE"
fi

for bt in $BUILD_TYPE; do

    if [ "x$SOURCE_DIR" != "x" ]; then
        CMAKE_ROOT="$SOURCE_DIR/build/cmake/$bt/$NAME";
    else
        SOURCE_DIR="$SDIR";
        if [ $DEVTREE -eq 1 ]; then
            CMAKE_ROOT="$SDIR/../build/$BRANCH/cmake/cmake/$bt/$NAME";
        else
            CMAKE_ROOT="$SDIR/build/cmake/$bt/$NAME";
        fi
    fi

    if [ "x$DO_DELETE" = "xyes" ]; then
        rm -rf $CMAKE_ROOT;
        print_info $CMAKE_ROOT deleted;
    fi

    if [ ! -e $CMAKE_ROOT ]; then
        mkdir -p $CMAKE_ROOT;
    fi

    # Always run cmake without the GUI first. This is because the GUI does not
    # accept command-line arguments and makes it more cumbersome to specify
    # the tool-chain file directly.
    if [ "x$CMAKE_G" != "x" ]; then
        $CMD_ECHO $CMAKE_BIN ${TOOLCHAIN_FILE:+"$TOOLCHAIN_FILE"} ${SYSTEM_FILE:+"$SYSTEM_FILE"} -G "$CMAKE_G" \
        	   $GIT_BRANCH $CMAKE_OPTIONS \
                $ENABLE_QUACK \
               -DCMAKE_MODULE_PATH="$RESOURCE_DIR/architectures" \
               -DCMAKE_BUILD_TYPE=$bt -DRTIME_TARGET_NAME=$NAME \
               -B$CMAKE_ROOT -H"$SOURCE_DIR" ;
    else
        $CMD_ECHO $CMAKE_BIN ${TOOLCHAIN_FILE:+"$TOOLCHAIN_FILE"} ${SYSTEM_FILE:+"$SYSTEM_FILE"} \
       			$GIT_BRANCH $CMAKE_OPTIONS \
                $ENABLE_QUACK \
          		-DCMAKE_MODULE_PATH="$RESOURCE_DIR/architectures" \
          		-DCMAKE_BUILD_TYPE=$bt -DRTIME_TARGET_NAME=$NAME \
                -B$CMAKE_ROOT -H"$SOURCE_DIR" ;
    fi;

    check_cmake_status "CMake configure"

    # If start the GUI if requested
    if [ "x$GUI" = "xyes" ]; then
        $CMD_ECHO $CMAKE_GUI -B$CMAKE_ROOT -H"$SOURCE_DIR";
    fi
done

if [ "x$CBUILD_OPTIONS" != "x" ]; then
    CBUILD_OPTIONS="-- $CBUILD_OPTIONS";
fi

for bt in $BUILD_TYPE; do
    if [ "x$DO_BUILD" = "xyes" ]; then
        $CMD_ECHO $CMAKE_BIN --build $CMAKE_ROOT --config $bt $CBUILD_OPTIONS;
        check_cmake_status "CMake build"
    fi
done
