/*
 * FILE: NETIOTester.h - NETIO Unit-test
 *
 * (c) Copyright, Real-Time Innovations, 2013-2020.
 *
 * All rights reserved.
 *
 * No duplications, whole or partial, manual or electronic, may be made
 * without express written permission.  Any such copies, or
 * revisions thereof, must display this notice unaltered.
 * This code contains trade secrets of Real-Time Innovations, Inc.
 *
 * Modification History
 * --------------------
 * 25febc2013,makehader  Created, Generated by makeheader
 *
 */
/*ce
 * \file
 * \brief Entrypoint for all netio unit tests
 */
#ifndef NETIOTester_pkg_h
#define NETIOTester_pkg_h

#include "osapi/osapi_types.h"

#ifdef __cplusplus
extern "C" {
#endif

extern unsigned char
NETIOTester_run(struct UTEST_Context *setting);

extern unsigned char
NETIOTester_start_ex(int beginSubmoduleTestIndex,
                     int beginUnitTestIndex,
                     int endSubmoduleTestIndex,
                     int endUnitTestIndex,
                     RTI_BOOL ignoreFailure,
                     const char* args);

extern unsigned char
NETIOTester_start(int beginSubmoduleTestIndex,
                  int beginUnitTestIndex,
                  int endSubmoduleTestIndex,
                  int endUnitTestIndex, 
                  RTI_BOOL ignoreFailure,
                  const char* intf_name);

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif /* NETIOTester_pkg_h */
