###############################################################################
# (c) Copyright, Real-Time Innovations 2016-2020
#
# All rights reserved.
# No duplications, whole or partial, manual or electronic, may be made
# without express written permission.  Any such copies, or
# revisions thereof, must display this notice unaltered.
# This code contains trade secrets of Real-Time Innovations, Inc.
#
################################################################################

INCLUDE(CMakeForceCompiler)
SET(_RTIME_OSAPI_PLATFORM autosar)

SET(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)

INCLUDE(${CMAKE_CURRENT_LIST_DIR}/platform.tc)

SET(RTIME_NO_SHARED_LIB TRUE)

SET(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
SET(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
SET(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
SET(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)

IF (DEFINED ENV{OSEK_PATH})
    STRING(REPLACE "\\" "/" VSTAR_PATH $ENV{OSEK_PATH})
ELSE()
    MESSAGE("Please set the OSEK_PATH environment variable. Example:")
    MESSAGE("set OSEK_PATH=c:\\AUTOSAR")
    MESSAGE(FATAL_ERROR "")
ENDIF()

INCLUDE_DIRECTORIES("${VSTAR_PATH}/VSTAR/BSWs/COM/TcpIp/ssc/inc")
INCLUDE_DIRECTORIES("${VSTAR_PATH}/VSTAR/BSWs/COM/TcpIp/ssc/ext/inc")
INCLUDE_DIRECTORIES("${VSTAR_PATH}/VSTAR/BSWs/Os/Os/core/ssc/inc")
INCLUDE_DIRECTORIES("${VSTAR_PATH}/VSTAR/BSWs/Os/Os/core/ssc/inc/internal")
INCLUDE_DIRECTORIES("${VSTAR_PATH}/VSTAR/BSWs/Os/Os/ssc/inc")
INCLUDE_DIRECTORIES("${VSTAR_PATH}/VSTAR/BSWs/RTE/Rte/ssc/inc")
INCLUDE_DIRECTORIES("${VSTAR_PATH}/VSTAR/BSWs/DIAG/Dem/ssc/inc")
INCLUDE_DIRECTORIES("${VSTAR_PATH}/VSTAR/BSWs/LIB/VSTAR_Bits/ssc/inc")

#ADD_DEFINITIONS(-DATOMICS_USE_GENERIC_IMPL=1)

IF (RTIME_TARGET_NAME MATCHES "Tasking")
    INCLUDE_DIRECTORIES("${VSTAR_PATH}/VSTAR/BSWs/Os/Os/ssc/compiler/Tasking/inc")
ENDIF()

IF (RTIME_TARGET_NAME MATCHES "^tc29xt")
    INCLUDE_DIRECTORIES("${VSTAR_PATH}/VSTAR/TTs/TriCore161/compiler_common/platform/TriBoard_TC29x/inc")
    SET(RTI_ENDIAN_LITTLE 1)
ELSE()
    MESSAGE(FATAL_ERROR "No architecture recognized, please select one from: tc29xt.")
ENDIF()

SET(RTIME_INCLUDE_AUTOSAR true)

ADD_DEFINITIONS(-DSTD_TYPES_AR_RELEASE_MAJOR_VERSION=OS_AR_RELEASE_MAJOR_VERSION)
ADD_DEFINITIONS(-DSTD_TYPES_AR_RELEASE_MINOR_VERSION=OS_AR_RELEASE_MINOR_VERSION)
ADD_DEFINITIONS(-DOS_RTM_H_SW_MAJOR_VERSION=OS_SW_MAJOR_VERSION)
ADD_DEFINITIONS(-DOS_RTM_H_SW_MINOR_VERSION=OS_SW_MINOR_VERSION)
ADD_DEFINITIONS(-DOS_LCFG_H_SW_MAJOR_VERSION=OS_SW_MAJOR_VERSION)
ADD_DEFINITIONS(-DOS_LCFG_H_SW_MINOR_VERSION=OS_SW_MINOR_VERSION)
ADD_DEFINITIONS(-DOS_CFG_H_SW_MAJOR_VERSION=OS_SW_MAJOR_VERSION)
ADD_DEFINITIONS(-DOS_CFG_H_SW_MINOR_VERSION=OS_SW_MINOR_VERSION)
ADD_DEFINITIONS(-DTCPIP_CFG_H_AR_MAJOR_VERSION=TCPIP_AR_RELEASE_MAJOR_VERSION)
ADD_DEFINITIONS(-DTCPIP_CFG_H_AR_MINOR_VERSION=TCPIP_AR_RELEASE_MINOR_VERSION)
ADD_DEFINITIONS(-DTCPIP_CFG_H_SW_MAJOR_VERSION=TCPIP_SW_MAJOR_VERSION)
ADD_DEFINITIONS(-DTCPIP_CFG_H_SW_MINOR_VERSION=TCPIP_SW_MINOR_VERSION)
ADD_DEFINITIONS(-DOS_CONFIG_SC1)
ADD_DEFINITIONS(-DOS_MCU_DERIVATIVE=TC297)
ADD_DEFINITIONS(-DOS_MEMMAP_HEADER="Os_MemMap.h")
ADD_DEFINITIONS(-DTCPIP_INCLUDE_IPV4=1)
ADD_DEFINITIONS(-DTCPIP_NET_BUFF_COUNT=100)
ADD_DEFINITIONS(-DTCPIP_NET_BUFF_SIZE=512)
ADD_DEFINITIONS(-DTCPIP_NET_TASK_COUNT=2)
ADD_DEFINITIONS(-DOS_CORE_NO=3)
ADD_DEFINITIONS(-DRTIME_AUTOSAR_EVENTMASK_TYPE=uint64)
