#!/bin/sh
#########################################################################
# (c) 2005-2014 Copyright, Real-Time Innovations. All rights reserved.  #
# No duplications, whole or partial, manual or electronic, may be made  #
# without express written permission.  Any such copies, or              #
# revisions thereof, must display this notice unaltered.                #
# This code contains trade secrets of Real-Time Innovations, Inc.       #
#########################################################################


filename=$0
script_dir="$(dirname "$filename")"
script_dir="$(cd "$script_dir" && pwd)"
application_name=rtiddsmag
script_version=
mag_dir="$(dirname "$script_dir")"
last_dir_name="$(basename "$script_dir")"

if [ "$last_dir_name" = "bin" ]; then
    mag_dir="${mag_dir}/rtiddsmag"
fi

arg_jre="-jre"
jre_path="some/made/up/path/that/likely/wont/exist"
jre_mode=PATH
#PATH            java from PATH
#SHIPPED         RTI-shipped jre
#JAVAHOME        JAVA_HOME
#JREHOME         JREHOME
#CMDLINE         -jre

stripped_dir="$(dirname ${script_dir})"
last_dir_name="$(basename "$(dirname "$filename")")"

if [ "$last_dir_name" = "bin" ]; then
    script_dir="${stripped_dir}/rtiddsmag/scripts"
fi

get_jre="false"
for arg in "$@"
do
    shift

    # only -jre argument handled by script
    if [ x"$arg" = x"$arg_jre" ]; then
        jre_mode=CMDLINE
        get_jre="true"
        continue
    elif [ "$get_jre" = "true" ]; then
        jre_path="$arg"
        get_jre="false"
        continue
    else
        set -- "$@" "$arg"
    fi
done

# Initialize ${arch} to a dummy value so that JREHOME will be properly
# initialized in the event that the OS is not recognized.
arch="some_dummy_value_to_be_overridden_later"
os=`uname -s`

case $os in
Linux*)
    cpu=`uname -p`
    if [ "unknown" = "$cpu" ]; then
        cpu=`uname -m`
    fi
    if [ "x86_64" = "$cpu" ]; then
        arch="x64Linux"
    else
        arch="i86Linux"
    fi
    ;;
Darwin*)
    cpu=`uname -p`
    if [ "$cpu" = "x86_64" ] || [ "$cpu" = "i386" ]; then
        arch="x64Darwin  darwin x64Darwin/Contents/Home darwin/Contents/Home"
    elif [ "$cpu" = "arm" ] || [ "$cpu" = "arm64" ]; then
        # Check if we are running under Rosetta 2 so we use the right directory
        if sysctl -n sysctl.proc_translated 2>/dev/null | grep -q "1"; then
            arch="x64Darwin darwin x64Darwin/Contents/Home darwin/Contents/Home"
        else
            arch="arm64Darwin arm64Darwin/Contents/Home"
        fi
    else
        echo "Warning: $cpu may not be supported. Be sure to specify a JRE to use with JREHOME."
    fi
    ;;
*)
    echo "Warning: OS $os may not be supported. Be sure to specify a JRE to use with JREHOME."
    ;;
esac

# If user specified -jre <path>, use that
if [ "$jre_mode" = "CMDLINE" ]; then
    if [ "$getJre" = "true" ]; then
        echo "ERROR: no path specified with option -jre"
        exit 1
    fi

    jre_path="$jre_path/bin/"
#use JREHOME if set
elif [ -n "$JREHOME" ]; then
    jre_mode=JREHOME
    if [ ! -d $JREHOME ]; then
        echo "ERROR: JREHOME=[$JREHOME] does not exist"
        exit 1
    fi
    jre_path="$JREHOME/bin/"

#use JAVA_HOME if set
elif [ -n "$JAVA_HOME" ]; then
    jre_mode=JAVAHOME
    if [ ! -d $JAVA_HOME ]; then
        echo "ERROR: JAVA_HOME=[$JAVA_HOME] does not exist"
        exit 1
    fi
    jre_path="$JAVA_HOME/bin/"

# use SHIPPED if available. First try local installation, then try Pro
# installation.
elif [ -d "$mag_dir/jre" ] || [ -d "$mag_dir/../../resource/app/jre" ]; then
    for p in "$mag_dir/jre" "$mag_dir/../../resource/app/jre"; do
        for a in $arch; do
            if [ -d "$p/$a/bin" ]; then
                jre_path="$p/$a/bin/"
                jre_mode=SHIPPED
                break
            fi
        done
        if [ "$jre_mode" = "SHIPPED" ]; then
            break
        fi
    done

    if [ "$jre_mode" != "SHIPPED" ]; then
        echo "ERROR: Did not find a suitable installed JRE in $mag_dir/jre or $mag_dir/../../resource/app/jre"
        exit 1
    fi
#default to PATH
else
    jre_mode=PATH
    jre_path=""
fi

java_bin="${jre_path}java"

app_support_dir=$script_dir/../resource
rtiddsmag_jar=$script_dir/../class/rtiddsmag.jar

if [ "$jre_mode" != "PATH" -a ! -x "$java_bin" ]; then
    echo "Cannot find or execute '$java_bin'. Be sure to specify the correct JRE to use."
    exit 2
fi

javaPrefsWarning="--add-opens=java.base/java.lang=ALL-UNNAMED"

java_version=$("${java_bin}" -version 2>&1 | awk -F '"' '/version/ {print $2}')
java_major_version=$(printf '%s' "$java_version" | awk -F '[^0-9]+' '{print $1}')
if [ -n "$java_major_version" ] && [ "$java_major_version" -ne 17 ]; then
    echo "warning: Micro Application Generator has not been tested with Java ${java_version}. Unexpected behavior may occur."
fi

exec "${java_bin}" \
-DMAG_RESOURCE_DIR="$app_support_dir" -DSCHEMA_DIR="$app_support_dir/schema" \
"$javaPrefsWarning" \
-jar "$rtiddsmag_jar" \
"$@" \
$optional_arguments

